### PR TITLE
ruby: rubocop: improve errorformat

### PR DESCRIPTION
**Pull request by blueyed**
I had this from somewhere in my local stash - maybe from Syntastic?!

@Neki 
Does it make sense?

### CODE REVIEW

**Comment by Neki** [comment]
I am not sure why you pinged me for this issue (I did not follow the development of Neomake for at least one year).

I am no longer using Ruby on a day-to-day basis either, so unfortunately I can not answer this.

**Comment by blueyed** [comment]
@Neki 
IIRC I've looked at the makers Git history and thought you would know probably.

Closing it then for now, maybe somebody finds it later.

**Comment by blueyed** [comment]
@bitboxer
Maybe you know about this?  (seen you starring rubocop-runner)

**Comment by bitboxer** [comment]
I am using rubocop. What do you want to know?

**Comment by blueyed** [comment]
@bitboxer 
If the suggested errorformat here might be better, i.e. are there errors without a column (`%c`).

I guess it could not hurt to have it covered anyway (maybe for older version only).. - and therefore merge it.
I just don't remember where I found it.

**Comment by bitboxer** [comment]
Will check it on the weekend and report back!

**Comment by bitboxer** [comment]
I played around with it and saw no case where the errors are worse. I think it could not hurt to have it.

**Comment by blueyed** [comment]
@bitboxer 
Thanks!

**Pull request merged**
