### PR TITLE
Add pdflatex-based tex maker.

### PR DESCRIPTION
**Pull request by glacambre**

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks!
I've pushed some fixups.  Please consider using a separate branch (and not master) for PRs in the future.

**Comment by blueyed** [comment]
Merged, thanks again.
Please add it to the wiki: https://github.com/neomake/neomake/wiki/Makers

**Comment by aldur** [comment]
@blueyed @glacambre now everytime a user runs `Neomake` `pdflatex` creates LaTeX auxiliary files in the current directory (i.e. aux, log, pdf, etc.).
This can be annoying for those that, like me, use latexmk with a custom build directory.

What do you guys think?

**Comment by blueyed** [comment]
> However, this is not portable.

Because of using `/tmp`?  Vim has `tempname()` that could be used.
Should it be stable across runs then?  (at least for the same file)

**Comment by languitar** [comment]
Getting pdflatex to do real out-of-source builds is a real pain.

But @aldur, you are free to just disable the maker again by defining `g:neomake_tex_enabled_makers`. ;)

**Comment by aldur** [comment]
@languitar, I agree about the usefulness and I disabled it, but I spent a few minutes to understand what was creating that files for me. Since it "pollutes" the user environment, it doesn't seem like a reasonable maker to be enabled by default.

**Comment by blueyed** [comment]
> it doesn't seem like a reasonable maker to be enabled by default.

Agreed.
It sounds we should not enable it by default, and also add `--output-directory`.  Do you agree?

**Comment by blueyed** [comment]
Can we use `--output-directory /dev/null`, or does it need to be a dir really?

**Comment by languitar** [comment]
Depends on the use case, generally, I would say. If pdflatex is used for linting, that would be ok. Otherwise, if someone would really want to use this to produce a PDF, that would be a bad idea.

**Comment by blueyed** [comment]
OK, disabled it for now, and added a note to https://github.com/neomake/neomake/wiki/Makers.
Thanks for your feedback!

**Pull request closed without merging**
