### PR TITLE
Go: serialize / prefer gometalinter

### PR DESCRIPTION
**Pull request by blueyed**
Some suggestions based on comments in https://github.com/neomake/neomake/pull/795.

### CODE REVIEW

**Comment by bradleyfalzon** [comment]
This looks good to me.

**Comment by blueyed** [comment]
> I still don't believe that linters should ever be errors, these should be reserved for the compiler

If gometalinter calls "go vet" and this "Reports potential errors that otherwise compile.", those should be marked as errors, no?  (have not checked if gometalinter would actually report them as errors though)

> as long as they aren't run if there's a Go compiler error.

That should be provided through `serialize` / `serialize_abort_on_error` now.
Please note that this should be improved, but it should work if `go test -c` (the `go` maker) exits non-zero (#1214).

**Comment by bradleyfalzon** [comment]
> If gometalinter calls "go vet" and this "Reports potential errors that otherwise compile.", those should be marked as errors, no? (have not checked if gometalinter would actually report them as errors though)

I don't believe gometalinter could reliably determine which issues are actual errors, but ultimately, if the code compiles, there are no errors - it's just warnings. Most of gometalinters checks are linters that help you out, "did you forget to check this error" and therefore aren't errors, just warnings as the code still compiles.

**Comment by blueyed** [comment]
Let's merge this then as-is for now (will squash the fixup)?!
/cc @novas0x2a @JelteF @mhinz @tweekmonster

**Pull request merged**
