### PR TITLE
Add languagetool maker for HTTP server

### PR DESCRIPTION
**Pull request by somini**
This adds a new text maker for languagetool, using the HTTP server.

This is #1728.

Defaults to a server @ `localhost:8081`.

See https://gist.github.com/somini/b3421a3c89bd6a6716de1123e39cefad for
socket activation systemd configuration.

### CODE REVIEW

**Comment by somini** [comment]
This is still a WIP, list of things to do:
- [ ] Allow server URL configuration. Just a dumb prefix to replace `http://localhost:8081/`, it's possible to run the service on HTTPS.
- [ ] Allow forcing language instead of reading from `spelllang`
- [ ] Allow configuration of "motherTongue". Default to nothing, to disable false friend detection.
- [ ] Tests

**Comment by somini** [comment]
There's a public languagetool server with some hefty rate limits, but it should be good to test this.

Use:
```vim
let g:neomake_text_languagetool_curl_server = "https://languagetool.org/api"
```

**Comment by somini** [comment]
Well, this works for ASCII text (1 character = 1 byte), but any non-ASCII text will break the offsets, making this worthless.
The languagetool output mentions an "offset", but it's not bytes, it's characters. The regular CLI output sends the correct line and column numbers, but the API won't.

That means this needs yet another overhaul.

**Comment by somini** [comment]
I added a very ugly hack to that non-ASCII bug I found. I'll be using this for a while to see if it's usable.
It's a terrible piece of code, I'm almost ashamed of pushing this into a public repo.

It still fails on edge cases such as an error alone in a line.

**Comment by blueyed** [comment]
Maybe it's easier to require/use Python for parsing/handling this?

**Comment by somini** [comment]
I could include a small python script that used urllib to make HTTP requests, mangle the JSON into a better JSON and the vimscript function to put that into entries.

There's even precedent:
https://github.com/neomake/neomake/tree/master/autoload/neomake/makers/ft/java
https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/java.vim#L122-L137

It would even eliminate the dependency on cUrl, it could be used on Windows.

I think I will go that way instead of the current horrible code. I'll open a new PR when I have something to show.

**Pull request closed without merging**
