### PR TITLE
Protobuf buf maker

### PR DESCRIPTION
**Pull request by Jumziey**
- Added a maker using bufbuild/buf (https://buf.build/)

- Removed prototools maker for protobuf files.

### CODE REVIEW

**Comment by Jumziey** [comment]
Ok, i need to fix that.

**Comment by blueyed** [comment]
Test failure for reference:
```
    (359/703) [EXECUTE] Instantiate all default makers
 
      > SKIP: Skipping haskell - expensive setup
 
      > [D +1.40]: Failed to get cargo metadata for workspace using 'cargo metadata --no-deps --format-version 1'.
 
    (359/703) [EXECUTE] (X) Errors when loading makers (per file):
 
 - autoload/neomake/makers/ft/proto.vim:
 
   - Could not load maker 'process_output_buf' for filetype proto: Vim(let):E119: Not enough arguments for function: neomake#makers#ft#proto#process_output_buf
 
      > /home/neomake/repo/tests/makers.vader:238: Assert 0, "Errors when loading makers (per file):".msg
 
    > NOTE: 1 error(s) in teardown (ignored with failing test).
 ```

**Comment by Jumziey** [comment]
i accidently broke my fork when trying to sync with upstream... i dunno how i managed to do that... so starting a new pr

**Comment by blueyed** [comment]
Ref: https://github.com/neomake/neomake/pull/2505

**Pull request closed without merging**
