### PR TITLE
statusline: prepend disabled-info always

### PR DESCRIPTION
**Pull request by blueyed**
Includes #1864.
New base for #1862?!

### CODE REVIEW

**Comment by somini** [comment]
Thanks for this and #1862. I'll take a look tomorrow.

**Comment by somini** [comment]
I can't push here, so closing in favour of #1862.

**Comment by somini** [comment]
I can't close this either.

**Comment by blueyed** [comment]
Included in https://github.com/neomake/neomake/pull/1862.

**Pull request closed without merging**
