### PR TITLE
Add idris maker

### PR DESCRIPTION
**Pull request by blueyed**
Continuation of https://github.com/neomake/neomake/pull/353.

### CODE REVIEW

**Comment by blueyed** [comment]
@majjoha 
Please provide some feedback.

See https://help.github.com/articles/checking-out-pull-requests-locally/ for how to checkout a PR locally.

**Comment by blueyed** [comment]
Well, it's tested and we can go from there.

Merry xmas, I hope you enjoy this improved maker.. :D

**Comment by blueyed** [comment]
@majjoha 
Please add it to the wiki: https://github.com/neomake/neomake/wiki/Makers.

**Comment by majjoha** [comment]
Sorry for the late response, but the new Idris maker works flawlessly. It is certainly far better than my initial attempt. Thanks, @blueyed!

I'll add the Idris maker to the wiki in a second.

**Comment by blueyed** [comment]
Thanks, I am glad you like it!

**Pull request closed without merging**
