### PR TITLE
add golangci-lint maker

### LINKED ISSUE #2319: Is it possible to integrate golangci-lint?
[Gometalinter](https://github.com/alecthomas/gometalinter) is already integrated.
Gometalinter is deprecated.
The author [recommends](https://github.com/alecthomas/gometalinter/issues/590#issue-407606165) switching to [golangci-lint](https://github.com/golangci/golangci-lint).

### PR DESCRIPTION
**Pull request by cenkalti**
Fix #2319

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks!

The patch not being covered is ok for the executable checks, but please consider adding a test based on real output.  See #2335 and other tests using `NeomakeTestsGetMakerWithOutput`.

**Comment by cenkalti** [comment]
I have added a test case for checking real output.

**Comment by blueyed** [comment]
Thanks!
Please add it to the wiki: https://github.com/neomake/neomake/wiki/Makers

**Comment by cenkalti** [comment]
Added!

**Pull request merged**
