### PR TITLE
[RFC] Expand %f in neomake#utils#ExpandArgs

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/neomake/neomake/issues/1191

### CODE REVIEW

**Comment by tweekmonster** [comment]
Hmm, I'm not sure if `%f` is the way to go for this, but I'm not against it.  I just want to point out that it might be semantically confusing.

`ExpandArgs()` takes `%` as a filename substitution as defined with Vim's `expand()` and `fnamemodify()`.  We use `%%` to prevent the expansion.  So, if an argument is passing a `printf()` style format string for floats, `%%f` would break in this case.

Maybe it'll be easier and more future-proof to set environment variables?  For example use `$NEOMAKE_TEMPFILE` in the arguments to let the system call sort it out?

**Comment by blueyed** [comment]
> Maybe it'll be easier and more future-proof to set environment variables?

Very nice idea, I'll change it.

**Comment by blueyed** [comment]
Not really sure how to approach this though: my current idea would be to `let $NEOMAKE_TEMPFILE` before starting the jobs, and unletting it afterwards again?!
Also it should be `NEOMAKE_FILENAME` probably (since it is about the file to be used, which usually is not a temporary file).

**Comment by blueyed** [comment]
Closing this in favor of https://github.com/neomake/neomake/pull/1207.

**Pull request closed without merging**
