### PR TITLE
Improve managing active jobs, and restart them directly

### PR DESCRIPTION
**Pull request by blueyed**
This manages active jobs in s:make_info, and keeps track of finished
ones.
It now restarts jobs for the same maker directly, instead of waiting for
the old one to do it from the exit handler.

### CODE REVIEW

**Comment by wwwdata** [comment]
I just updated my plugins and suddenly my eslint checks weren't working anymore. After a couple of checking out old neomake commits I found that this PR was breaking it for me. Is there anything needed to update in the neomake configuration to make this change work?

Here is my neomake info. Looks like it finds my eslint and wants to use it. I am using some more name spacing for flow checks and so on:

```
#### Neomake debug information
Async support: 1
Current filetype: javascript.jsx.flow

##### Enabled makers
For the current filetype (with :Neomake):
 - eslint
   - args: ['-f', 'compact']
   - auto_enabled: 0
   - errorformat: '%E%f: line %l\, col %c\, Error - %m,%W%f: line %l\, col %c\, Warning - %m'
   - exe: '/Users/benbieker/Development/someprojectname/node_modules/.bin/eslint'
   - fts: ['javascript']
   - remove_invalid_entries: 1
NOTE: you can define g:neomake_javascript.jsx.flow_enabled_makers to configure it (or b:neomake_javascript.jsx.flow_enabled_makers).

For the project (with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings

g:neomake_error_sign = {'texthl': 'NeomakeErrorSign', 'text': ''}
g:neomake_flow_enabled_makers = []
g:neomake_info_sign = {'texthl': 'NeomakeInfoSign', 'text': ''}
g:neomake_javascript_enabled_makers = ['eslint']
g:neomake_javascript_eslint_exe = '/Users/benbieker/Development/guestlist-app/node_modules/.bin/eslint'
g:neomake_jsx_enabled_makers = []
g:neomake_message_sign = {'texthl': 'NeomakeMessageSign', 'text': ''}
g:neomake_open_list = 2
g:neomake_place_signs = 1
g:neomake_remove_invalid_entries = 1
g:neomake_warning_sign = {'texthl': 'NeomakeWarningSign', 'text': ''}

Windows: 0
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
```

**Comment by wwwdata** [comment]
After checking out commit by commit, this one is the problematic one eeb023e3b54d3251e8c594e0697ef048201f8d6b

**Comment by blueyed** [comment]
@wwwdata 
Fixed in https://github.com/neomake/neomake/pull/1124.

**Comment by wwwdata** [comment]
cool thanks @blueyed it works for me again!

**Pull request merged**
