### PR TITLE
Add directory maker for sbt

### LINKED ISSUE #1472: Creating a directory maker for SBT
Hello,

I'm trying to create a maker for SBT (with the intention of contributing it), and I'm not sure if I'm doing this right. Here's my maker:

```vim
let g:neomake_sbtcompile_maker = {
    \ 'exe': 'sbt',
    \ 'args': ['compile'],
    \ 'errorformat': '[%trror] %f:%l: error: %m'
\ }
```

Which I run with `Neomake! sbtcompile`. And here's an example SBT error that I would like to match:

```
[info] Loading project definition from /path/to/projroot/project
[info] Set current project to ProjName (in build file:/path/to/projroot)
[info] Compiling 1 Scala source to /path/to/projroot/ProjName/target/scala-2.11/classes...
[error] /path/to/projroot/and/stuff/MyClass.scala:4: not found: object mypackage
[error] import mypackage._
[error]        ^
[error] 1 errors found
```

It doesn't seem to find any errors. Is there something obviously wrong with my maker/errorformat or the way I'm doing this?

(I know I can make this more sophisticated by matching the number of spaces on the next line with `%p` to find the column number, but right now I'm just trying to get the basic thing working.)

### PR DESCRIPTION
**Pull request by McBrainy**
[sbt](https://github.com/sbt/sbt) is the "simple build tool" for Scala, Java, etc.

This fixes #1472.

### CODE REVIEW

**Comment by blueyed** [comment]
What filetypes is this meant for?  I assume `java` and `scala`?

I'm asking because of https://github.com/neomake/neomake/pull/1452 - i.e. should this be a project maker really?

**Comment by McBrainy** [comment]
It's mainly for Java and Scala. My understanding is that it should be a project maker because (1) it operates on an entire project (specified by a `build.sbt` configuration file) and (2) it can't take a file as an argument. It's a build tool in the same category as Maven or Gradle. But I don't understand the subtleties of the linked PR, so it's really up to you.

**Comment by blueyed** [comment]
I'll take it as-is, thanks.
Please add it to the wiki's maker list.

**Comment by McBrainy** [comment]
Done.

**Pull request merged**
