### PR TITLE
Add NeomakeJobStarted/NeomakeJobInit hooks, allowing to set niceness

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/neomake/neomake/issues/1271.

TODO:
 - [x] doc

### CODE REVIEW

**Comment by blueyed** [comment]
@stamm 
Any feedback on this?

**Comment by stamm** [comment]
@blueyed sorry for long delay. Can you advise me how to use it?

**Comment by blueyed** [comment]
@stamm 
Does looking at the tests (which are examples by itself) help you?  https://github.com/neomake/neomake/pull/1273/files#diff-8c055ff6d7936d3eea8f8bf67d1c9555R33

If it is more about testing this PR see https://help.github.com/articles/checking-out-pull-requests-locally/.

**Comment by blueyed** [comment]
@stamm 
Have you looked into it?

**Pull request merged**
