### PR TITLE
Improve Travis integration: linting

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
Should be green for now, but only `vint-errors` is required to pass:
https://travis-ci.org/blueyed/neomake/builds/133748148

**Comment by blueyed** [comment]
Should be ready.
Current build is: https://travis-ci.org/blueyed/neomake/builds/133773874

I plan to merge this soon and will then re-enable Travis for PRs.

**Comment by wsdjeg** [comment]
please add an build status icon into readme.md

**Comment by blueyed** [comment]
Done.  Also enabled Travis again - it should show up here.
I will merge it when it's green again/still.

**Pull request merged**
