### PR TITLE
[RFC] Doc: fix tag syntax

### PR DESCRIPTION
**Pull request by mhinz**

### CODE REVIEW

**Comment by blueyed** [comment]
LGTM, thanks!
Should I merge it?
I would be happy to add you as a contributor - just let me know and you're in! :)

**Comment by mhinz** [comment]
> Should I merge it?

Yup, those 2 occurences were the only ones with a superfluous `:h`, most probably added by accident.

> I would be happy to add you as a contributor - just let me know and you're in! :)

Well, I still have to read up on the code, but if you think that I could be of any help, count me in!

**Comment by blueyed** [comment]
Thanks!
You're in! :)

**Comment by blueyed** [comment]
btw: please don't go overboard with too involving code changes / refactoring, given that I am cooking something already..  should have some more time for this next week(end) hopefully.

**Pull request merged**
