### PR TITLE
added crystal as a maker for crystal

### PR DESCRIPTION
**Pull request by sbdchd**

### CODE REVIEW

**Comment by blueyed** [comment]
LGTM, can you also please add it to the README?

**Comment by sbdchd** [comment]
Done

**Comment by blueyed** [comment]
This needs to be rebased, since the README is gone to the wiki.
I've tried to `hub am` it, but failed.

**Comment by sbdchd** [comment]
I will have to make a new pull request since I deleted the branch & repo that this pull request was based on.

**Pull request closed without merging**
