### PR TITLE
Update makers/ft/php.vim from Syntastic

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/neomake/neomake/issues/896

### CODE REVIEW

**Comment by still-dreaming-1** [comment]
I want to try this out, but I don't quite see.. where it is. Doesn't a pull request normally come from a forked repository?

**Comment by mhinz** [comment]
@still-dreaming-1 They can come from any branch. Also from the same repo. At the bottom of each PR page there's a small message like this one:

```
Add more commits by pushing to the fix-php branch on neomake/neomake
```

So.. it's here! 

```
$ git fetch origin refs/pull/900/head && git checkout FETCH_HEAD 
```

**Comment by blueyed** [comment]
Yep.. and for the full documentation/help about this see https://help.github.com/articles/checking-out-pull-requests-locally/.

**Comment by still-dreaming-1** [comment]
Ah, I got it now I. I was confused because I did actually look for that branch, but I just didn't see if for some reason. Anyway, this works great, thanks! I find it interesting that telling php to show the errors fixed my issue. I did try running `php -l` in the terminal and got the same generic error. I wonder what changed as I did not have this problem until now?

**Comment by blueyed** [comment]
> I wonder what changed as I did not have this problem until now?

A PHP update with new defaults?!
Some config change of your own?

**Pull request merged**
