### PR TITLE
`g:neomake_open_list`: Prevent original window from jumping around

### PR DESCRIPTION
**Pull request by nfnty**

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks!

How and when is it jumping around for you, and what is your config for `neomake_open_list`?

Given the async nature however, we should be extra careful here (and not jump also for `open_val` already).
Instead of the `wincmd p`, what about `exe w "wincmd w"`, where w is the window ID, if available?
See `win_getid()`, `win_gotoid()` etc.
Normal window numbers and window IDs should be compatible (the latter starting at 1000).

A test for this would be nice, but if you can provide a manual test case, we can come up with a Vader test together.

See also https://github.com/neomake/neomake/issues/805, and https://github.com/neomake/neomake/projects/1.

**Comment by nfnty** [comment]
The problem I'm referring to is when lines of the original window jump to a new position with respect to the terminal window when opening new splits.

This should probably be fixed by new autocommand events like `WinResizePre` and `WinResizePost`. Not by implementing this in every plugin that opens a new window.

**Comment by blueyed** [comment]
So I guess you are not using `set noequalalways` then - which seems to be a very non-default setting, but I am using it.

**Comment by nfnty** [comment]
That's not the problem. Here you can see what I'm referring to:

***Without this PR***
vim_bad

***With this PR***
vim_good

**Comment by blueyed** [comment]
I would need to investigate - I am not using `neomake_open_list` myself, and `set noequalalways`, which might be relevant in this context: can you try it?

Apart from that I am OK with merging this for now as-is.

**Comment by nfnty** [comment]
Don't merge this yet, I'm working on making a real fix for neovim instead.

**Comment by blueyed** [comment]
Is it only a problem with Neovim then, but not Vim?

**Comment by nfnty** [comment]
No, this is a problem that's always been there, I've just not used quickfix windows extensively until now.

**Comment by blueyed** [comment]
I've tried to reproduce this today, and for me the view was jumping back after closing the location/quickfix list (after going up when it opened)?!  (but my config might be involved, similar to yours)
This PR however would improve the behavior, but it really looks more like a Vim/Neovim and/or config issue.

I'm looking forward to your findings.. :)

**Comment by blueyed** [comment]
This is likely fixed/improved by https://github.com/neomake/neomake/commit/d786a43c88b801ac5bf123733b8ffbad7d08d3b9.

**Pull request closed without merging**
