### PR TITLE
add correct maker.version_args for javac and checkstyle

### PR DESCRIPTION
**Pull request by davidosomething**

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks!

I wonder if we should try at least `-v` always, if `--version` fails?
Then `-version` could also be tried maybe?

**Comment by davidosomething** [comment]
@blueyed  i think it should only run if `version_arg` is provided.

e.g. `bashate` (https://docs.openstack.org/bashate/latest/readme.html) is a linter that uses `-v` for "verbose output" and doesn't have a version flag at all.  
I haven't added it as an upstream maker since there's no way to skip running the linter exe for version retrieval

**Comment by blueyed** [comment]
> i think it should only run if version_arg is provided.

But defaulting to `--version` is OK still, isn't it?

**Comment by blueyed** [comment]
Feel free to merge this as-is then.

**Comment by davidosomething** [comment]
How should I merge without the coverage test pass? Manually merge to master and push?

**Pull request merged**
