### PR TITLE
s:ProcessEntries: use bufnr from entries if present

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/neomake/neomake/pull/1123#issuecomment-288536452.

### CODE REVIEW

**Comment by JelteF** [comment]
Seems like a fix that makes sense.

**Comment by JelteF** [comment]
It's probably nice to move this code from #1123 to the mapping code:
```vim
        let l:error.bufnr = bufnr(l:error.filename)
        if l:error.bufnr == -1
            execute 'badd ' . l:error.filename
            let l:error.bufnr = bufnr(l:error.filename)
        endif
```

**Comment by blueyed** [comment]
@JelteF 
maybe, yes - but is it required after all?  Wouldn't the filename be there still, and the buffer opened/added when selecting this list entry?

**Comment by JelteF** [comment]
I tried that first. But the difference is that then you have to run the the maker again after opening the file, otherwise the signs are not added. The other version opens a buffer automatically for each found file it seemed.

**Comment by blueyed** [comment]
> otherwise the signs are not added

Ah, that's another issue with signs then I would say: they should be queued and added once the buffer gets opened.

**Comment by blueyed** [comment]
@JelteF 
I think it's fine to keep in #1123 for now, but should be marked as TODO, with a reference to here, or explaining it there.

**Comment by JelteF** [comment]
Sounds like a good approach

**Pull request merged**
