### PR TITLE
Add contrib/vim-checks, adopted from ALE

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by w0rp** [comment]
You need to include the copyright notice and what not from the BSD licence for ALE: https://github.com/w0rp/ale/blob/master/LICENSE

**Comment by blueyed** [comment]
@w0rp 
Thanks for letting me know.
I assume a LICENSE file with a note about the affected file in `contrib/LICENSE` is fine for this?

**Comment by blueyed** [comment]
I will rather add it to the file itself.

**Comment by blueyed** [comment]
Do you think https://github.com/neomake/neomake/pull/1248 is good enough for this?

**Pull request closed without merging**
