### PR TITLE
Implement  #361: highlight columns

### PR DESCRIPTION
**Pull request by mhartington**
This is a rebased version of #361 that adds highlights to not only the side column, but the line column as well.

TODO:
 - [ ] check if supported (for older Vim)
 - [ ] tests

### CODE REVIEW

**Comment by bounceme** [comment]
It might be good to have a fallback for matchaddpos which was added vim 7.4.330

**Comment by blueyed** [comment]
Can you create the PR from a branch, please? - so only relevant changes show up here?  (I guess you have to create a new PR for that then).  Or reset your master to only include this PR until it is merged.

**Comment by blueyed** [comment]
> It might be good to have a fallback for matchaddpos, which was added vim 7.4.330

I'd say only if it's easy: otherwise you just cannot use it.. but this should be checked then (`has('*matchaddpos')`).

**Comment by mhartington** [comment]
Closing as #361 is updated again. Sorry for the noise!

**Pull request closed without merging**
