### PR TITLE
add swift maker

### PR DESCRIPTION
**Pull request by dhcmrlchtdj**

### CODE REVIEW

**Comment by blueyed** [comment]
There is also https://github.com/neomake/neomake/pull/392.
Does it make sense to enable both at once?

**Comment by brendanjerwin** [comment]
I bet it does. Linters and compilers like peanut butter and chocolate... I'll try it out and see if it rocks.

**Comment by VDKA** [comment]
It maybe nice to use SwiftPM if the directory contains a `Package.swift` file.

**Comment by blueyed** [comment]
There we go, thanks!

**Comment by keith** [comment]
I've created a PR for SwiftPM support https://github.com/neomake/neomake/pull/1890

**Pull request closed without merging**
