### PR TITLE
Fix vimhelplint violations

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/neomake/neomake/issues/600.

Rebased https://github.com/neomake/neomake/pull/685.

### CODE REVIEW

**Comment by davidosomething** [comment]
blocked by #690

**Comment by blueyed** [comment]
Well, the one from this PR is the one with the most votes currently.

**Comment by blueyed** [comment]
Looks like I messed up the debase though: https://github.com/neomake/neomake/pull/692/files#diff-0209e2cd5670892a1f78ee3c87ffcf37R25

**Comment by davidosomething** [comment]
GH has a Squash and Merge option when merging now, do you even need to do that

**Comment by blueyed** [comment]
@davidosomething 
> GH has a Squash and Merge option when merging now, do you even need to do that

That does not work with conflicts.. :)
(the conflicts came from the vim-async merge)

**Pull request merged**
