### PR TITLE
add write-good support

### PR DESCRIPTION
**Pull request by Alok**
The last pull request for this didn't respond for a month.

I implemented the functionality you asked for that pull request.

### CODE REVIEW

**Comment by Alok** [comment]
I also added write-good to the wiki.

**Comment by blueyed** [comment]
Let's keep it at https://github.com/neomake/neomake/pull/653, no?
My last comment was asking for you to report back there.
Have you addressed my other remarks?

**Comment by blueyed** [comment]
You can force-push this branch to the other PR.

**Comment by blueyed** [comment]
But please rebase it into a single commit - or make it ready to be squash-merged.

**Comment by Alok** [comment]
How do I force-push to the other PR? I'm not very familiar with most git commands. I rebased it to a single commit.

I did address all of your remarks.
- returns the markdown autoload functions
- adds abort to each function
- added to wiki

**Comment by blueyed** [comment]
Oh, the other PR wasn't from you.  Re-opening this one then.
But you should have used another branch instead of master.
What about creating a new PR based on a separate branch (just do `git checkout -b add-write-good-support`, push that and create the PR from there).
Thanks!

**Pull request closed without merging**
