### PR TITLE
vulture is supported, so add it to the README file

### PR DESCRIPTION
**Pull request by jabbalaci**
Vulture (a new Python maker) was merged here: https://github.com/neomake/neomake/pull/420 . Let's indicate it in the README file too.

### CODE REVIEW

**Comment by blueyed** [comment]
Please sort it to the end, link to the home page (https://bitbucket.org/jendrikseipp/vulture ?!) and mention that it is not enabled by default (in brackets).

**Comment by jabbalaci** [comment]
OK, link added to the home page.

**Comment by blueyed** [comment]
Thanks!

**Comment by jabbalaci** [comment]
I'm glad I could contribute. If anyone is interested how to use vulture (as it is not enabled by default), here is the corresponding part of my `init.vim`:

```
Plug 'neomake/neomake'
" {{{
    " neomake is async => it doesn't block the editor
    " It's a syntastic alternative. Syntastic was slow for me on python files.
    " $ sudo pip2/pip3 install flake8 -U
    " $ sudo pip2/pip3 install vulture -U
    let g:neomake_python_enabled_makers = ['flake8', 'pep8', 'vulture']
    " let g:neomake_python_enabled_makers = ['flake8', 'pep8']
    " E501 is line length of 80 characters
    let g:neomake_python_flake8_maker = { 'args': ['--ignore=E115,E266,E501'], }
    let g:neomake_python_pep8_maker = { 'args': ['--max-line-length=100', '--ignore=E115,E266'], }

    " run neomake on the current file on every write:
    autocmd! BufWritePost * Neomake
" }}}
```

**Pull request merged**
