### PR TITLE
make lintr output readable for human

### PR DESCRIPTION
**Pull request by yech1990**

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks!
Can you provide some example output which could be added to a test then?

How does it (the raw outpu) look with and without the new options?

**Comment by yech1990** [comment]
When start a new R process, R will generate a long header message and restore workspace from current directory, which will disrupt and slow down the linter.

> Without arguments:

image


> With the new arguments:

image

**Comment by blueyed** [comment]
Thanks for the info, but can you paste this, please? :)

**Comment by yech1990** [comment]
The output of current version.
```bash
||
|| R version 3.5.3 (2019-03-11) -- "Great Truth"
|| Copyright (C) 2019 The R Foundation for Statistical Computing
|| Platform: x86_64-pc-linux-gnu (64-bit)
||
|| R is free software and comes with ABSOLUTELY NO WARRANTY.
|| You are welcome to redistribute it under certain conditions.
|| Type 'license()' or 'licence()' for distribution details.
||
||   Natural language support but running in an English locale
||
|| R is a collaborative project with many contributors.
|| Type 'contributors()' for more information and
|| 'citation()' on how to cite R or R packages in publications.
||
|| Type 'demo()' for some demos, 'help()' for on-line help, or
|| 'help.start()' for an HTML browser interface to help.
|| Type 'q()' to quit R.
||
|| > lintr::lint("/home/user/Coding/learn_r/test.R")
test.R|12 col 1 warning| lines should not be more than 80 characters.
||   flow_df, aes(y = Freq, x = time, alluvium = leaf_id, stratum = progenitor, fill = progenitor)
|| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|| >
|| >
|| [Previously saved workspace restored]
||
```

The only useful message:

```bash
test.R|12 col 1 warning| lines should not be more than 80 characters.
||   flow_df, aes(y = Freq, x = time, alluvium = leaf_id, stratum = progenitor, fill = progenitor)
```

and `no-restore` speed up the plugin.

**Comment by blueyed** [comment]
Thanks.  The output might be useful to create some tests later.

**Pull request merged**
