### PR TITLE
doc: statusline: format_status

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/vim-airline/vim-airline/issues/1567#issuecomment-336712410

### CODE REVIEW

**Comment by blueyed** [comment]
@teto 
Ping

**Comment by teto** [comment]
Sorry I am pretty busy lately. Will give it  a try this week, hopefully monday.

**Comment by teto** [comment]
The simpler statusline seems to work but I wish airline would make it easier to use your original one.

**Comment by blueyed** [comment]
It has no good test coverage (like before), but I'll merge this anyway for now.

The issue with airline is something different.

**Pull request merged**
