### PR TITLE
Fix an eslint_d issue

### PR DESCRIPTION
**Pull request by sei40kr**
# Changes

Fix an issue eslint_d invokes global ESLint for local project files.

### CODE REVIEW

**Comment by blueyed** [comment]
Necessary for eslint then also I guess?!

**Comment by blueyed** [comment]
Found an old branch where it gets merged: https://github.com/neomake/neomake/pull/1844.
Do you agree that `cwd` should be used for both?

**Comment by sei40kr** [comment]
@blueyed 
I read eslint-cli source code and diff in the PR above. And I agree that.

**Comment by blueyed** [comment]
Thanks!

**Pull request merged**
