### PR TITLE
typescript: improve tsc maker

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/neomake/neomake/issues/720#issuecomment-255521531
Closes https://github.com/neomake/neomake/pull/565.
Ref: https://github.com/neomake/neomake/pull/494.

### CODE REVIEW

**Comment by blueyed** [comment]
Wow, nobody cares?

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for improving tsc maker. I wrote this maker back then neomake or typescript does not support project/tsconfig. Thanks for the big improvement.

I might be wrong, but is the pattern "%:p" needed to be changed to "%:h:p" ? neomake currently breaks on my machine.

**Comment by blueyed** [comment]
> is the pattern "%:p" needed to be changed to "%:h:p" ?

Yes.
Then it works for you?

**Comment by HerringtonDarkholme** [comment]
Yes, works like a charm.

**Comment by blueyed** [comment]
Awesome.  Thanks for reporting the issue and the fix!

**Pull request merged**
