### PR TITLE
Fix #569

### LINKED ISSUE #569: Fix vimlint errors with Java maker
There are 3 issues with the Java maker:
```
./autoload/neomake/makers/ft/java.vim:137:31:Error: EVL103: unused argument `a:classpathFile`
./autoload/neomake/makers/ft/java.vim:369:65:Error: EVL104: variable may not be initialized on some execution path: `l:cp`
./autoload/neomake/makers/ft/java.vim:359:29:Error: EVL102: unused variable2 `l:classes`
```

@wsdjeg 
Can you take a look at them, please?

Ref: #437 

I'll look at the other ones that sneaked in, since this job is allowed to fail, which I'd like to change.

### PR DESCRIPTION
**Pull request by wsdjeg**
@blueyed  sorry,Line 137 can not be fixed.

### CODE REVIEW

**Comment by blueyed** [comment]
You can fix it like this:
```diff
diff --git i/autoload/neomake/makers/ft/java.vim w/autoload/neomake/makers/ft/java.vim
index 5728533..77088d7 100644
--- i/autoload/neomake/makers/ft/java.vim
+++ w/autoload/neomake/makers/ft/java.vim
@@ -134,6 +134,7 @@ function! s:AddToClasspath(classpath, path) abort
     return (a:classpath !=# '') ? a:classpath . s:ClassSep() . a:path : a:path
 endfunction
 
+" @vimlint(EVL103, 1, a:classpathFile)
 function! s:ReadClassPathFile(classpathFile) abort
     let cp = ''
     let file = g:neomake_java_checker_home. s:psep. 'java'. s:psep.  'classpath.py'
@@ -148,6 +149,7 @@ function! s:ReadClassPathFile(classpathFile) abort
     endif
     return cp
 endfunction
+" @vimlint(EVL103, 0)
```

Followup: https://github.com/neomake/neomake/pull/742

**Comment by blueyed** [comment]
Thanks, finally we can enable vimlint-errors.

**Comment by wsdjeg** [comment]
Got it. will do it.

**Comment by blueyed** [comment]
?

I did it already 👍

**Comment by wsdjeg** [comment]
nice, thanks

**Pull request closed without merging**
