### PR TITLE
hide [no test files] line for go maker

### PR DESCRIPTION
**Pull request by cenkalti**
When there are no test files, go command prints an output line similar to:
```
?   	github.com/cenkalti/rain/rainrpc	[no test files]
```

This line does not need to be visible on location list. This PR makes a change to hide that line.

### CODE REVIEW

**Comment by blueyed** [comment]
Not sure why the test fails, but it should be modernized anyway: you can cherry-pick / use https://github.com/neomake/neomake/pull/2335 already, and then adjust the output for what you are testing maybe (or add new test base on this).

**Comment by cenkalti** [comment]
This is done I guess.

**Comment by blueyed** [comment]
ok.. I've renamed the test - or do I miss something?
can you fix the conflict now, please?
(move it to the other "go: go" test)

**Comment by blueyed** [comment]
Sorry for noticing it only now, but this should rather go into the errorformat, using `%-G…`.

**Comment by cenkalti** [comment]
I didn't know that `%-G` existed for this purpose. I guess it can be merged now.

**Comment by blueyed** [comment]
Thanks!

**Pull request merged**
