### PR TITLE
Fix statusline formatting with empty string

### PR DESCRIPTION
**Pull request by somini**
If the input string is empty, the output includes some detritus like `-q`.

### CODE REVIEW

**Comment by blueyed** [comment]
Can you provide an example / where you've run into this issue?

**Comment by somini** [comment]
I have tried to reproduce this but I can't.

I was configuring Lightline to have a Neomake section, and reached this:
https://gitlab.com/somini/dotnvim/blob/master/init.vim#L1399-1410
It might be a fluke in my environment or a bug on Lightline.
I remember restarting Neovim and getting the same result, but it's gone now. Sorry about that.

**Comment by blueyed** [comment]
I've tried to reproduce it based on your config (which is interesting btw), but could not.

```diff
--- i/tests/statusline.vader
+++ w/tests/statusline.vader
@@ -59,6 +59,46 @@ Execute (LoclistCounts for wiped buffer should clean s:loclist_counts):
   call setbufvar(g:neomake_test_countschanged[0].bufnr, 'test', 1)
   AssertEqual '', getbufvar(g:neomake_test_countschanged[0].bufnr, 'test')

+Execute (neomake#statusline#get_status):
+  new
+  let bufnr = bufnr('')
+  let good_glyph = '✓'
+  let type_glyph = {
+    \ 'E': '✖',
+    \ 'W': '⚠',
+    \ 'I': 'ℹ',
+    \ 'M': '➤',
+    \ }
+    let options = {
+      \ 'format_running': '{{running_job_names}}⚒',
+      \ 'format_loclist_ok': good_glyph,
+      \ 'format_loclist_unknown': '⋯',
+      \ 'format_quickfix_issues:': '⌖%s',
+      \ 'format_status': '⌘%s',
+      \ }
+  for [ftype, string] in items(type_glyph)
+    let options['format_loclist_type_'.ftype] = '{{count}}'.string
+    let options['format_quickfix_type_'.ftype] = '{{count}}'.string
+  endfor
+  AssertEqual neomake#statusline#get_status(bufnr, options), '⋯'
+
+  CallNeomake {'enabled_makers': [g:error_maker]}
+  AssertEqual neomake#statusline#get_status(bufnr, options), '1✖'
+
+  let maker = {}
+  function! maker.get_list_entries(...)
+    return [{'type': 'U', 'text': 'unknown_type', 'lnum': 1}]
+  endfunction
+  CallNeomake {'enabled_makers': [maker]}
+  AssertEqual neomake#statusline#get_status(bufnr, options), good_glyph
+
+  call neomake#Make({'enabled_makers': [g:sleep_maker]})
+  if neomake#has_async_support()
+    AssertEqual neomake#statusline#get_status(bufnr, options), 'sleep-maker⚒'
+  endif
+  NeomakeCancelJobs!
+  bwipe
+
 Execute (neomake#statusline#get_status):
   let bufnr = bufnr('')
   AssertEqual neomake#statusline#get_status(bufnr, {}), '?'
```

**Comment by blueyed** [comment]
The next time it would be helpful to have the "traceback" (function calls) from Vim that lead to the error.

**Comment by somini** [comment]
Thanks for merging this.
It might have been some fluke, I should have stopped the world and produce a proper bug report. At least that test will catch similar issues, and I can improve it if it ever happens again.

**Pull request merged**
