### PR TITLE
Improve java makers

### PR DESCRIPTION
**Pull request by paretje**
I improved the javac maker to support multiline errors, thanks to Syntastic. I also added a checkstyle maker.

### CODE REVIEW

**Comment by wsdjeg** [comment]
hi @paretje
can you see #375

**Comment by paretje** [comment]
I'm sorry for the late reply @wsdjeg. If you cherry pick the commit of the checkstyle maker, this PR could be come redundant.

As I see you made use of vim variables for ie the classpath, you might be interested in adding a variable for the checkstyle file. I didn't because you can do this by overriding the maker args.

**Comment by wsdjeg** [comment]
thanks for supporting checkstyle,I will merged this PR to my fork branch.no need to close this PR.It will be auto merged.

I will finish it this weekend.

**Comment by wsdjeg** [comment]
local merged

**Pull request closed without merging**
