### PR TITLE
signs: use a default set for hltext setting

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/neomake/neomake/issues/204
Supersedes https://github.com/neomake/neomake/pull/248

### CODE REVIEW

**Comment by blueyed** [comment]
@casimir @eugen0329 @demon386 (from #248)
@andrewbredow @jrolfs (from #204)

Can you give this a try, please?

**Comment by casimir** [comment]
With [ParperColor](https://github.com/NLKNguyen/papercolor-theme) theme it's still color-less. I will look at configuring color in my rc when I have some time.

**Comment by blueyed** [comment]
@casimir 
You mean the background is not adopted from there?

**Comment by casimir** [comment]
Looks like I had something wrong in my setup. After a cleanup it's all good. I have the sign and the color now. Thank you @blueyed.

**Pull request merged**
