### PR TITLE
[blocked upstream] parse tslint JSON output

### LINKED ISSUE #1783: Typescript TSLint ignores warnings
### Expected behavior

When TSLint has a warning, that's displayed as a warning within Neovim.

### Steps to reproduce

1. Set up TSLint for a project
2. Make a change to a file that results in a warning.
3. Nothing shows up.

### The Problem

The problem seems to be in this [line of code](https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/typescript.vim#L27). It looks like the code is only looking for `ERROR` in the output and ignoring lines that begin with `WARNING`. I fixed it locally by changing the code to this:

```
\ 'errorformat': '%EERROR: %f[%l\, %c]: %m,%WWARNING: %f[%l\, %c]: %m',
```

I'd be happy to contribute a PR unless you guys would like to do it. 😃

### PR DESCRIPTION
**Pull request by euclio**
This passes warning and span information on to neomake.

Fixes #1783.

### CODE REVIEW

**Comment by euclio** [comment]
Hm, this isn't quite working yet. Looks like tslint doesn't like temporary files.

**Comment by blueyed** [comment]
What is the problem with tempfiles?
I assume that it is because of `'filename': data.name`?

I am seeing "No valid rules have been specified" on stderr with the minimal example I have for testing.

When using `'output_stream': 'stdout'` this gets transformed into an error from Neomake: `Neomake: tslint: unexpected output on stderr: No valid rules have been specified`, and otherwise the decoding of the JSON will fail.
Therefore having `output_stream` makes sense.

btw: there is an open issue for tslint to handle stdin, which would help here: https://github.com/palantir/tslint/issues/1590.

**Comment by blueyed** [comment]
My `tsconfig.json`:
```json
{ "rules": {
    "noUnusedParameters": true
} }
```

Tried an empty one also.  What am I missing?

**Comment by euclio** [comment]
It's not easy to reproduce, but I was getting an intermittent error where tslint would complain that the temp file isn't part of the project, which would cause the JSON parsing to blow up.

**Comment by blueyed** [comment]
Ah, similar to what I was seeing then.
Can you help me with getting a test case for this, i.e. a `tsconfig.json` that should work?

**Comment by euclio** [comment]
Ah, got it to happen. Use this tsconfig.json:

```
{
    "files": [ "t.ts" ]
}
```

And then open t.ts and start typing a bunch. Without `tempfile_enabled: 0`, you'll get an error.

**Comment by blueyed** [comment]
Still getting "No valid rules have been specified"..
Using tslint 5.9.1 on Arch Linux.

**Comment by euclio** [comment]
I'm testing with this tslint.json:

```
{
    "defaultSeverity": "error",
    "extends": [
        "tslint:recommended"
    ],
    "jsRules": {},
    "rules": {
        "no-console": {
            "severity": "warning",
            "items": ["log"]
        }
    },
    "rulesDirectory": []
}
```

**Comment by blueyed** [comment]
That works.

Your error is because it is not included in "files" it seems.

> X is not included in project.

It seems like using `-p` enforces this check..
Adding `"include": [ ".*.ts" ]` to tsconfig.json seems to help here - and appears to be required for an empty "files" setting (to explicitly include hidden files).

Not sure how to proceed here really, but disabling tempfiles is a bid bad, since automaking (without saving) is not possible then.

**Comment by euclio** [comment]
Perhaps disable tempfiles by default and document that you can reenable it to fix automaking if you have `".*.ts` in your tsconfig?

**Comment by blueyed** [comment]
Or not using `-p` by default.. what is the reason for this again?  To have typechecks?  Aren't those provided via `tsc` already?

**Comment by euclio** [comment]
That flag determines the list of files to be linted, and also enables some additional checks that require type information. Imo, it should be enabled if available.

**Comment by euclio** [comment]
Sounds like https://github.com/palantir/tslint/issues/1590 is really the best solution, though.

**Comment by blueyed** [comment]
Yeah.

> the list of files to be linted

IIRC tslint ignores this for when an argument is passed, except for the check apparently if it is in the project.. :/

But I see that it is good to keep it then.

A hack coming to mind would be to create a temp `tsconfig.json` that would add `.*@neomake*.ts` to `include` - not that trivial though.. ;)

I agree that disabling tempfiles with `-p` is good for now then, and document the workaround.
Although we do not really have documentation for makers itself currently AFAIR - might be the best adding it to the wiki then for now.

I would also like to test
1. how the "unexpected output" behaves with automaking - if it shows up all the time that would be annoying
2. how disabled tempfiles interact with automaking: it should just skip the automaking then with a debug msg, possibly warning once.

**Comment by blueyed** [comment]
Pushed some fixup (inline the JSON/output), and covered the usage of tsconfig.json.

**Comment by blueyed** [comment]
btw: I plan to add a wrapper that helps with parsing JSON output: https://github.com/neomake/neomake/issues/1795 (can be done later for this though).

**Comment by euclio** [comment]
What remains to be done here?

**Comment by blueyed** [comment]
The tests mentioned above, but not really related to the PR.
I will have to look into it, might take me a few days.

**Comment by euclio** [comment]
Looks like the unexpected output will pop up whenever you edit a file not in the project. Probably best to just test if the first character is `[`.

**Comment by blueyed** [comment]
We can use `filter_output` to get rid of it.

**Comment by blueyed** [comment]
`process_json` has been merged by now (#1848), so could (and should) be used here.

**Comment by euclio** [comment]
Awesome. Added them in the latest commit.

**Comment by davidosomething** [comment]
i wonder if recently merged #2010 json updates will help here?

**Comment by euclio** [comment]
@davidosomething This is effectively blocked on https://github.com/palantir/tslint/pull/3816

**Comment by blueyed** [comment]
I am closing this for now, given that there appears to be no work done upstream for this.
Happy to re-open later, of course.

**Pull request closed without merging**
