### PR TITLE
Fix quoting of argv for Vim on Windows

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/neomake/neomake/issues/959

### CODE REVIEW

**Comment by jsfaint** [comment]
This PR Not works for me 😢 
But with the following patch on master branch 8f6aba3531c81a3d3d291721f7515f8efa2e59f8, it works now
```
diff --git a/autoload/neomake.vim b/autoload/neomake.vim
index 75436d7..2fa6035 100644
--- a/autoload/neomake.vim
+++ b/autoload/neomake.vim
@@ -291,9 +291,7 @@ function! s:maker_base.get_argv(...) abort dict
             let argv = exe . (len(args) ? ' ' . args : '')
         endif
         if !has('nvim')
-            if neomake#utils#IsRunningWindows()
-                let argv = &shell.' '.&shellcmdflag.' '.shellescape(args_is_list ? join(argv) : argv)
-            elseif !args_is_list
+            if !args_is_list
                 let argv = [&shell, &shellcmdflag, argv]
             endif
         endif
```

**Comment by blueyed** [comment]
@jwmng
Does this also work for you?

**Comment by blueyed** [comment]
@jsfaint 
Would be good to remove this special case after all, thanks for looking into it!

I think this PR or in general I've tried to take the following into account (from `:h job_start`):
> {command} can be a String.  This works best on MS-Windows.  On Unix it is split up in white-separated parts to be passed to execvp().  Arguments in double quotes can contain white space.

But if the shell workaround works in general, it might be good.

Any chance that you or @jwmng could run the test suite?
See https://github.com/neomake/neomake/issues/724 - it would be nice to have CI for it after all.

**Comment by blueyed** [comment]
Updated this PR/branch according to @jsfaint's patch.

**Comment by jwmng** [comment]
Running the test suite using Vader in gvim, will put results at #724

**Comment by blueyed** [comment]
@jwmng 
And does the updated PR fix it for you already (when using, not with the tests)?

**Comment by jwmng** [comment]
Forgot to mention that yes it works fine

**Comment by blueyed** [comment]
Thanks!

**Pull request merged**
