### PR TITLE
add haxe lint

### LINKED ISSUE #216: Maker for Haxe?
Hi, i use neovim with vaxe and neomake. Before neomake, i did the syntax checks with syntastic.

Is there a way to check haxe syntax with neomake?

Regards, Dan

### PR DESCRIPTION
**Pull request by davidosomething**
fix #216

### CODE REVIEW

**Comment by blueyed** [comment]
Pushed a fixup.
Please squash-merge.

**Comment by davidosomething** [comment]
can you restart the circleci builds? they seem to be stuck on github

**Comment by blueyed** [comment]
The config changed, close+reopen should work usually to retrigger a build.

**Comment by blueyed** [comment]
Rebased/squashed now.

**Pull request merged**
