### PR TITLE
Fix style with autoload/neomake/makers/ft/{s,}css.vim

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by davidosomething** [comment]
that's the way i like it :)

**Comment by davidosomething** [comment]
although i prefer to put the concat operator on the next line so you can delete the line at will without having a stray `.`

**Comment by blueyed** [comment]
@davidosomething 
I think you can pick any other ft maker plugin file and do the same.. ;) - I just reviewed those and then did it.

**Comment by blueyed** [comment]
> although i prefer to put the concat operator on the next line so you can delete the line at will without having a stray `.`

I'll keep that in mind and tend to do it myself, but I did not want to refactor it.. ;)

**Comment by blueyed** [comment]
@davidosomething 
The downside however is that you need to indent the first line to align the errorformat entries, so I am rather -0 on this in this context.

**Pull request merged**
