### PR TITLE
Coverage reporting

### PR DESCRIPTION
**Pull request by blueyed**
Based on https://github.com/Vimjas/covimerage.

### CODE REVIEW

**Comment by blueyed** [comment]
:fireworks:

**Comment by blueyed** [comment]
@wsdjeg 
You might be interested in https://codecov.io/gh/neomake/neomake/src/master/autoload/neomake/makers/ft/java.vim ;)

**Comment by wsdjeg** [comment]
looks nice!

**Comment by blueyed** [comment]
Yeah! (apart from the missing coverage ;))

https://github.com/Vimjas/covimerage is meant to allow this for every Vim plugins / scripts.

**Comment by wsdjeg** [comment]
@blueyed I have looked for this tools for long time, and I want to add coverage reporting feature for SpaceVim. Thanks.

**Comment by blueyed** [comment]
Yes, me too.
Therefore I've decided to build it finally.

**Comment by blueyed** [comment]
Please let me know about any issues.
See Neomake's integration of covimerage, but in general the README should cover everything - so please report any issues you might find.

**Comment by wsdjeg** [comment]
@blueyed I just add codecov.yml in SpaceVim, But I can not get it work, I just read the readme of covimerage, but still can not get it. can you help to send me a PR?

**Comment by blueyed** [comment]
@wsdjeg 
I am working on simplifying the setup, so that you should be able to use
`covimerage run` then.

I will look into creating a PR / helping you once that is pushed.

**Comment by wsdjeg** [comment]
@blueyed Thank you.

**Pull request merged**
