### PR TITLE
added proselint for .tex

### PR DESCRIPTION
**Pull request by sbdchd**
As suggested by @jonhoo in #338

### CODE REVIEW

**Comment by blueyed** [comment]
Please also add it to the README (and check if it's up to date for that filetype).

**Comment by poohzrn** [comment]
@blueyed ping

**Comment by blueyed** [comment]
I do not like to have multiple `neomake#makers#ft#X#proselint` functions.. (which we already seem to have)
There should be a leading one.

Otherwise this LGTM, but needs to be rebased.

**Comment by poohzrn** [comment]
This one can be closed as of #775

**Comment by blueyed** [comment]
Thanks!
This can be closed then, right?

The list of makers has been moved to the README.
@poohzrn 
Can you please update it as of #775?

**Comment by poohzrn** [comment]
@blueyed will do!

**Pull request closed without merging**
