### PR TITLE
Added xo type checker

### PR DESCRIPTION
**Pull request by ranisalt**
Adds [sindresorhus/xo](https://github.com/sindresorhus/xo) linter, which is heavily based on eslint

### CODE REVIEW

**Comment by blueyed** [comment]
Does is make sense to run both xo and eslint then by default?
Or should one of them get preferred?
You could check for this with `executable` - see other makers, e.g. the python one.

**Comment by ranisalt** [comment]
I will take a look closely later

**Comment by aymericbeaumet** [comment]
@blueyed eslint is more popular so it should be the default, plus it's not opinionated.

Also the options are slightly different, here is what I use:

```
        let g:neomake_javascript_xo_maker = {
        \   'args': [ '--compact' ],
        \   'errorformat': '%E%f: line %l\, col %c\, Error - %m,' .
        \                  '%W%f: line %l\, col %c\, Warning - %m',
        \ }
```

**Comment by blueyed** [comment]
@aymericbeaumet 
Can you create a PR for that then, please?

This PR here seems to make sense nonetheless, right?

**Comment by blueyed** [comment]
I see now.. if `eslint` is available, should it get used instead of all other makers, i.e. is it a meta-maker, like pylama for Python?

**Comment by aymericbeaumet** [comment]
`eslint` is not a metalinter, it's just a configurable linter.
`xo` has been built on the top of `eslint`, and brings an opinionated configuration.

PR: https://github.com/neomake/neomake/pull/561

**Pull request closed without merging**
