### PR TITLE
Clone of #1218 with added test case

### PR DESCRIPTION
**Pull request by JelteF**
This highlights the issue that I was having and shows why I created
get_or_create_buffer. If another file is open an no bufnr is given the current
bufnr is used.

### CODE REVIEW

**Comment by blueyed** [comment]
Hmm, the 3 commits from you all seem to fail in the same way?!

I am looking into https://github.com/neomake/neomake/pull/1257 now again.. my guess is that rebasing this on top of it would fix it.

**Comment by JelteF** [comment]
The revert is of the wrong commit should be of yours, but is of my second one

**Comment by JelteF** [comment]
Should be fixed now

**Comment by JelteF** [comment]
Hmm, still fails. Locally it works for me with `nvim +Vader tests/ft_rust.vader`.

**Comment by blueyed** [comment]
How about just `make tests/ft_rust.vader`?
`nvim +Vader tests/ft_rust.vader` works,, but there are teardown checks that it does not catch: `(6/7) [EXECUTE] (X) Vim(let):E94: No matching buffer for src/add_assign_like.rs`.

**Comment by blueyed** [comment]
(a new check added)

**Comment by blueyed** [comment]
Might be running into something odd like https://github.com/vim/vim/issues/1676 after all.
I can reproduce this to be OK with `nvim +Vader tests/ft_rust.vader` however.

**Comment by JelteF** [comment]
With the last commit it should be OK. The one before should be broken.

**Comment by blueyed** [comment]
Should be fixed now.. #1257 helped, and then it was also affected by https://github.com/vim/vim/issues/1676.

I will clean it up and merge it when it's really green.

**Comment by blueyed** [comment]
Pushed, thanks!

**Pull request closed without merging**
